routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Front\Homepage;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\Posts;
use App\Http\Controllers\Admin\Categories;
use App\Http\Controllers\Admin\Pages;
use App\Http\Controllers\Admin\Gallery;
use App\Http\Controllers\Admin\Settings;



/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::prefix('user')->middleware('check.login')->group(function ()
{
    Route::get(
        '/login',
        [Dashboard::class, 'login']
    )->name('login');

    Route::post(
        '/login',
        [Dashboard::class, 'loginPost']
    )->name('login.post');

    Route::get(
        '/create',
        [Dashboard::class, 'create']
    )->name('create.user');

    Route::post(
        '/create',
        [Dashboard::class, 'createUserPost']
    )->name('create.user.post');
});

Route::prefix('user')->middleware('check.auth')->group(function ()
{
    Route::get(
        '/dashboard',
        [Dashboard::class, 'index']
    )->name('dashboard');

    Route::get(
        '/logout',
        [Dashboard::class, 'logout']
    )->name('logout');

    Route::post(
        '/update/user/{id}',
        [Dashboard::class, 'update']
    )->name('user.update');


    // Post Routes
    // ------------------- //
    Route::delete(
        '/posts/{id}/delete',
        [Posts::class, 'delete']
    )->name('postdelete');

    Route::get(
        '/posts/trashed',
        [Posts::class, 'trashed']
    )->name('trashedbox');

    Route::resource(
        '/posts',
        Posts::class
    );
    // ------------------- //


    // Category Routes
    // ------------------- //

    Route::resource(
        '/categories',
        Categories::class
    );
    // ------------------- //


    // Page Routes
    // ------------------- //
    Route::delete(
        '/pages/{id}/delete',
        [Pages::class, 'delete']
    )->name('pagedelete');

    Route::get(
        '/pages/trashed',
        [Pages::class, 'trashed']
    )->name('pagetrashedbox');

    Route::resource(
        '/pages',
        Pages::class
    );
    // ------------------- //

    // Gallery Routes
    // ------------------- //

    Route::resource(
        '/gallery',
        Gallery::class
    );

    // ------------------- //

    // Setting Routes
    // ------------------- //

    Route::resource(
        '/settings',
        Settings::class
    );

    // ------------------- //
});

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get(
    '/',
    [Homepage::class, 'index']
)->name('homepage');

Route::post(
    '/settings/mode',
    [Homepage::class, 'changeMode']
)->name('changeMode');

Route::get(
    '/{ctg}',
    [Homepage::class, 'categorypage']
)->name('categorypage');

Route::get(
    '/page/{slug}',
    [Homepage::class, 'pagepage']
)->name('pagepage');

Route::get(
    '/{ctg}/{slug}',
    [Homepage::class, 'singlepage']
)->name('singlepost');

app/Http/Controllers/Admin/Gallery.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Str;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class Gallery extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user'] = Auth::user();

        $data['images'] = File::files(public_path('gallery/'));

        // return $data['images'][0]->getRelativePathname();

        return view('admin.gallery.index', $data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data['user'] = Auth::user();

        if ( $request->hasFile('galleryimage') )
        {
            $imageName = 'image'.'-'.rand(11111, 99999).'.'.$request->file('galleryimage')->getClientOriginalExtension();
            $destinationPath = 'gallery';
            $upload_success = $request->file('galleryimage')->move($destinationPath, $imageName);

            if( $upload_success )
            {
                $data['messages'] = array(
                    'type' => 'success',
                    'text' => 'Image successfully updated.',
                    'name' => $imageName,
                    'link' => 'http://127.0.0.1:8000/'.$upload_success
                );
            }
            else
            {
                $data['messages'] = array(
                    'type' => 'danger',
                    'text' => 'Image could not updated.',
                    'name' => NULL,
                    'link' => NULL
                );
            }
        }
        else
        {
            $data['messages'] = array(
                'type' => 'danger',
                'text' => 'Image could not updated.',
                'name' => NULL,
                'link' => NULL
            );
        }

        $data['images'] = File::files(public_path('gallery/'));

        return view('admin.gallery.index', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data['user'] = Auth::user();

        File::delete(public_path('gallery/'. $id));

        $data['images'] = File::files(public_path('gallery'));

        return view('admin.gallery.index', $data);
    }
}

resources/views/admin/gallery/index.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Gallery')


@section('title', 'Gallery')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

<div class="section-body">
  <div class="row mt-4">
    <div class="col-12 col-md-12 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h4>Upload İmage</h4>
        </div>
        <div class="card-body">
          <form method="post" action="{{route('gallery.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label>File</label>
              <input type="file" class="form-control" name="galleryimage" value="{{ old('categoryslug') ?? '' }}">
            </div>
            <div class="form-group text-right">
                <button type="submit" class="btn btn-primary btn-lg btn-icon icon-right" name="submit">
                    Upload
                </button>
            </div>
        </form>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-12 col-lg-8">
      @if ($messages ?? '')
        <div class="alert alert-{{$messages['type'] ?? ''}} alert-dismissible show fade">
          <div class="alert-body">
            <button class="close" data-dismiss="alert">
              <span>×</span>
            </button>
            {{$messages['text'] ?? ''}}
            @if( $messages['link'] )
            <p id="link" onclick="copy()">{{$messages['link'] ?? ''}} <i class="fas fa-copy"></i></p>
            <script>
              function copy() {
                var copyText = document.getElementById("link").innerText;
                var elem = document.createElement("textarea");
                document.body.appendChild(elem);
                elem.value = copyText;
                elem.select();
                document.execCommand("copy");
                document.body.removeChild(elem);
                alert("Copied the text");
              }
            </script>
            @endif
          </div>
        </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4>Gallery</h4>
        </div>
        <div class="card-body">
          <div class="gallery gallery-md">
            @foreach ($images as $image)
            <div class="gallery-item" data-image="{{'/gallery/'.$image->getRelativePathname()}}"
              data-title="{{$image->getRelativePathname()}}" href="{{'/gallery/'.$image->getRelativePathname()}}"
              title="{{$image->getRelativePathname()}}" style="height:175px;width:175px;padding:5px;background-image: url(&quot;{{'/gallery/'.$image->getRelativePathname()}}&quot;);">
              <a href="{{ route('gallery.destroy', ['gallery'=> $image->getRelativePathname()]) }}"
              class="btn btn-icon btn-sm btn-danger" onclick="event.preventDefault();
              document.getElementById('delete-form-{{$image->getRelativePathname()}}').submit();">
                <i class="fas fa-trash-alt"></i>
              </a>
              <form id="delete-form-{{$image->getRelativePathname()}}" action="{{ route('gallery.destroy', ['gallery'=> $image->getRelativePathname()]) }}"
                method="POST" style="display: none;">
                @method('DELETE');
                @csrf
              </form>
            </div>
            @endforeach
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection