routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Front\Homepage;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\Posts;
use App\Http\Controllers\Admin\Categories;
use App\Http\Controllers\Admin\Pages;
use App\Http\Controllers\Admin\Gallery;
use App\Http\Controllers\Admin\Settings;



/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::prefix('user')->middleware('check.login')->group(function ()
{
    Route::get(
        '/login',
        [Dashboard::class, 'login']
    )->name('login');

    Route::post(
        '/login',
        [Dashboard::class, 'loginPost']
    )->name('login.post');

    Route::get(
        '/create',
        [Dashboard::class, 'create']
    )->name('create.user');

    Route::post(
        '/create',
        [Dashboard::class, 'createUserPost']
    )->name('create.user.post');
});

Route::prefix('user')->middleware('check.auth')->group(function ()
{
    Route::get(
        '/dashboard',
        [Dashboard::class, 'index']
    )->name('dashboard');

    Route::get(
        '/logout',
        [Dashboard::class, 'logout']
    )->name('logout');

    Route::post(
        '/update/user/{id}',
        [Dashboard::class, 'update']
    )->name('user.update');


    // Post Routes
    // ------------------- //
    Route::delete(
        '/posts/{id}/delete',
        [Posts::class, 'delete']
    )->name('postdelete');

    Route::get(
        '/posts/trashed',
        [Posts::class, 'trashed']
    )->name('trashedbox');

    Route::resource(
        '/posts',
        Posts::class
    );
    // ------------------- //


    // Category Routes
    // ------------------- //

    Route::resource(
        '/categories',
        Categories::class
    );
    // ------------------- //


    // Page Routes
    // ------------------- //
    Route::delete(
        '/pages/{id}/delete',
        [Pages::class, 'delete']
    )->name('pagedelete');

    Route::get(
        '/pages/trashed',
        [Pages::class, 'trashed']
    )->name('pagetrashedbox');

    Route::resource(
        '/pages',
        Pages::class
    );
    // ------------------- //

    // Gallery Routes
    // ------------------- //

    Route::resource(
        '/gallery',
        Gallery::class
    );

    // ------------------- //

    // Setting Routes
    // ------------------- //

    Route::resource(
        '/settings',
        Settings::class
    );

    // ------------------- //
});

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get(
    '/',
    [Homepage::class, 'index']
)->name('homepage');

Route::post(
    '/settings/mode',
    [Homepage::class, 'changeMode']
)->name('changeMode');

Route::get(
    '/{ctg}',
    [Homepage::class, 'categorypage']
)->name('categorypage');

Route::get(
    '/page/{slug}',
    [Homepage::class, 'pagepage']
)->name('pagepage');

Route::get(
    '/{ctg}/{slug}',
    [Homepage::class, 'singlepage']
)->name('singlepost');

resources/views/admin/pages/create.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Blog')


@section('title', 'New Page')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

            @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible show fade">
              <div class="alert-body">
                <button class="close" data-dismiss="alert">
                  <span>×</span>
                </button>
                {{$error}}
              </div>
            </div>
            @endforeach
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form method="POST" action="{{route('pages.store')}}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Title</label>
                                        <div class="col-sm-12 col-md-8">
                                            <input type="text" class="form-control" name="title" value="{{ old('title') ?? '' }}" autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Content</label>
                                        <div class="col-sm-12 col-md-8">
                                            <textarea id="froala" name="content">{{ old('content') ?? '' }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Description</label>
                                        <div class="col-sm-12 col-md-8">
                                            <textarea class="form-control" name="description" style="height:100px">{{ old('description') ?? '' }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Tags</label>
                                        <div class="col-sm-12 col-md-8">
                                            <input type="text" class="form-control" name="tags" value="{{ old('tags') ?? '' }}" autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Tumbnail</label>
                                        <div class="col-sm-12 col-md-8">
                                            <div id="image-preview" class="image-preview">
                                                <label for="image-upload" id="image-label">Choose File</label>
                                                <input type="file" name="tumbnail" id="image-upload" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Slug</label>
                                        <div class="col-sm-12 col-md-8">
                                            <input type="text" class="form-control" name="slug" value="{{ old('slug') ?? '' }}" autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Order</label>
                                        <div class="col-sm-12 col-md-8">
                                            <input type="text" class="form-control" name="order" value="{{ old('order') ?? '' }}" autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Status</label>
                                        <div class="col-sm-12 col-md-8">
                                            <select class="form-control" name="status">
                                                <option value="1">Publish</option>
                                                <option value="2">Draft</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2"></label>
                                        <div class="col-sm-12 col-md-8">
                                            <button type="submit" class="btn btn-primary btn-lg btn-icon icon-right" name="submit">
                                                Create
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

@section('summernotecss')
<link href="https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('summernotejs')
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js"></script>


<script>
    var editor = new FroalaEditor('#froala', {
        height: 300,
        quickInsertEnabled: false
    });
</script>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Blog')


  @section('title', 'Edit Page')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

            @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible show fade">
              <div class="alert-body">
                <button class="close" data-dismiss="alert">
                  <span>×</span>
                </button>
                {{$error}}
              </div>
            </div>
            @endforeach
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                            @foreach ($pages as $page)
                            <form method="POST" action="{{route('pages.update', ['page'=> $page->id])}}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Title</label>
                                    <div class="col-sm-12 col-md-8">
                                        <input type="text" class="form-control" name="title" value="{{ $page->title ?? '' }}" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Content</label>
                                    <div class="col-sm-12 col-md-8">
                                        <textarea id="froala" name="content">{{ $page->content ?? '' }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Description</label>
                                    <div class="col-sm-12 col-md-8">
                                        <textarea class="form-control" name="description" style="height:100px">{{ $page->description ?? '' }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Tags</label>
                                    <div class="col-sm-12 col-md-8">
                                        <input type="text" class="form-control" name="tags" value="{{ $page->tags ?? '' }}" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Tumbnail</label>
                                    <div class="col-sm-12 col-md-8">
                                        <div id="image-preview" class="image-preview">
                                            @if ($page->tumbnail != NULL)
                                            <img src="{{ $page->tumbnail ?? '' }}" width="320" height="300">
                                            @endif
                                            <label for="image-upload" id="image-label" >Choose File</label>
                                            <input type="file" name="tumbnail" id="image-upload" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Slug</label>
                                    <div class="col-sm-12 col-md-8">
                                        <input type="text" class="form-control" name="slug" value="{{ $page->slug ?? '' }}" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Order</label>
                                    <div class="col-sm-12 col-md-8">
                                        <input type="text" class="form-control" name="order" value="{{ $page->order ?? '' }}" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2">Status</label>
                                    <div class="col-sm-12 col-md-8">
                                        <select class="form-control" name="status">
                                            <option value="1">Publish</option>
                                            <option value="2">Draft</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row mb-4">
                                    <label class="col-form-label text-md-right col-12 col-md-2 col-lg-2"></label>
                                    <div class="col-sm-12 col-md-8">
                                        <button type="submit" class="btn btn-primary btn-lg btn-icon icon-right" name="submit">
                                            Update
                                        </button>
                                    </div>
                                </div>
                            </form>
                            @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

@section('summernotecss')
<link href="https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('summernotejs')
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js"></script>

<script>
    var editor = new FroalaEditor('#froala', {
        height: 300,
        quickInsertEnabled: false
    });
</script>

@endsection

resources/views/admin/pages/index.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Blog')


  @section('title', 'Pages')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card mb-0">
        <div class="card-body">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="nav-link active" href="#">All <span class="badge badge-white">10</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" >Draft <span class="badge badge-primary"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-12">
      @if ($messages ?? '')
        <div class="alert alert-{{$messages['type'] ?? ''}} alert-dismissible show fade">
          <div class="alert-body">
            <button class="close" data-dismiss="alert">
              <span>×</span>
            </button>
            {{$messages['text'] ?? ''}}
          </div>
        </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4>All Pages</h4>
        </div>
        <div class="card-body">
          <div class="float-left">
            <select class="form-control selectric">
              <option>Action For Selected</option>
              <option>Move to Draft</option>
              <option>Move to Pending</option>
              <option>Delete Permanently</option>
            </select>
          </div>
          <div class="float-right">
            <form>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-append">
                  <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <div class="clearfix mb-3"></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <tr>
                <th class="pt-2">
                  <div class="custom-checkbox custom-checkbox-table custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                      class="custom-control-input" id="checkbox-all">
                    <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                  </div>
                </th>
                <th>Title</th>
                <th>Created At</th>
                <th>Views</th>
                <th>Order</th>
                <th>Status</th>
              </tr>
              @foreach ($pages as $item)
              <tr>
                <td>
                  <div class="custom-checkbox custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                      id="{{$item->id}}">
                    <label for="{{$item->id}}" class="custom-control-label">&nbsp;</label>
                  </div>
                </td>
                <td>{{\Illuminate\Support\Str::limit($item->title, 60)}}
                  <div class="table-links">
                    <a href="{{route('pagepage',[$item->slug])}}">View</a>
                    <div class="bullet"></div>
                    <a href="{{route('pages.edit', ['page'=> $item->id])}}">Edit</a>
                    <div class="bullet"></div>
                    <a href="{{ route('pagedelete', ['id'=> $item->id]) }}"
                    class="text-danger" onclick="event.preventDefault();
                    document.getElementById('delete-form-{{ $item->id }}').submit();">
                      Trash
                    </a>
                    <form id="delete-form-{{ $item->id }}" action="{{ route('pagedelete', ['id'=> $item->id]) }}"
                      method="POST" style="display: none;">
                      @method('DELETE');
                      @csrf
                    </form>
                </td>

                <td>{{$item->created_at}}</td>
                <td>{{$item->hit}}</td>
                <td>{{$item->order}}</td>
                <td>
                  @if ($item->status == 0)
                  <div class="badge badge-warning">Drafted</div>
                  @else
                  <div class="badge badge-info">Published</div>
                  @endif
                </td>
              </tr>
              @endforeach
            </table>
          </div>

          <div class="float-right">
            <nav>
                {{$pages->links("pagination::bootstrap-4")}}
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/pages/trash.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Blog')


@section('title', 'Trash')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

@foreach ($errors->all() as $error)
  <div class="alert alert-danger alert-dismissible show fade">
    <div class="alert-body">
      <button class="close" data-dismiss="alert">
        <span>×</span>
      </button>
      {{$error}}
    </div>
  </div>
@endforeach


<div class="section-body">
  <div class="row mt-4">
    <div class="col-12">
      @if ($messages ?? '')
        <div class="alert alert-{{$messages['type'] ?? ''}} alert-dismissible show fade">
          <div class="alert-body">
            <button class="close" data-dismiss="alert">
              <span>×</span>
            </button>
            {{$messages['text'] ?? ''}}
          </div>
        </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4>
            Trashed Posts
          </h4>
          @if ( $pages[0] == NULL )
              <div class='text-danger'>Empty</div>
          @endif
        </div>
        <div class="card-body">
          <div class="float-left">
            <select class="form-control selectric">
              <option>Action For Selected</option>
              <option>Move to Draft</option>
              <option>Move to Pending</option>
              <option>Delete Permanently</option>
            </select>
          </div>
          <div class="float-right">
            <form>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-append">
                  <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <div class="clearfix mb-3"></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <tr>
                <th class="pt-2">
                  <div class="custom-checkbox custom-checkbox-table custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                      class="custom-control-input" id="checkbox-all">
                    <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                  </div>
                </th>
                <th>Title</th>
                <th>Created At</th>
                <th>Views</th>
                <th>Order</th>
                <th>Status</th>
              </tr>
              @foreach ($pages as $item)
              <tr>
                <td>
                  <div class="custom-checkbox custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                      id="{{$item->id}}">
                    <label for="{{$item->id}}" class="custom-control-label">&nbsp;</label>
                  </div>
                </td>
                <td>{{\Illuminate\Support\Str::limit($item->title, 60)}}
                  <div class="table-links">
                    <a href="{{route('pagepage',[$item->slug])}}">View</a>
                    <div class="bullet"></div>
                    <a href="{{route('pages.edit', ['page'=> $item->id])}}">Edit</a>
                    <div class="bullet"></div>
                    <a href="{{ route('pages.destroy', ['page'=> $item->id]) }}"
                    class="text-danger" onclick="event.preventDefault();
                    document.getElementById('delete-form-{{ $item->id }}').submit();">
                      Destroy
                    </a>
                    <form id="delete-form-{{ $item->id }}" action="{{ route('pages.destroy', ['page'=> $item->id]) }}"
                      method="POST" style="display: none;">
                      @method('DELETE');
                      @csrf
                    </form>
                </td>

                <td>{{$item->created_at}}</td>
                <td>{{$item->hit}}</td>
                <td>{{$item->order}}</td>
                <td>
                  @if ($item->deleted_at != NULL)
                  <span class="badge badge-danger">Deleted</span>
                  @endif
                </td>
              </tr>
              @endforeach
            </table>
          </div>

          <div class="float-right">
            <nav>
                {{$pages->links("pagination::bootstrap-4")}}
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection