routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Front\Homepage;
use App\Http\Controllers\Admin\Dashboard;
use App\Http\Controllers\Admin\Posts;
use App\Http\Controllers\Admin\Categories;
use App\Http\Controllers\Admin\Pages;
use App\Http\Controllers\Admin\Gallery;
use App\Http\Controllers\Admin\Settings;



/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::prefix('user')->middleware('check.login')->group(function ()
{
    Route::get(
        '/login',
        [Dashboard::class, 'login']
    )->name('login');

    Route::post(
        '/login',
        [Dashboard::class, 'loginPost']
    )->name('login.post');

    Route::get(
        '/create',
        [Dashboard::class, 'create']
    )->name('create.user');

    Route::post(
        '/create',
        [Dashboard::class, 'createUserPost']
    )->name('create.user.post');
});

Route::prefix('user')->middleware('check.auth')->group(function ()
{
    Route::get(
        '/dashboard',
        [Dashboard::class, 'index']
    )->name('dashboard');

    Route::get(
        '/logout',
        [Dashboard::class, 'logout']
    )->name('logout');

    Route::post(
        '/update/user/{id}',
        [Dashboard::class, 'update']
    )->name('user.update');


    // Post Routes
    // ------------------- //
    Route::delete(
        '/posts/{id}/delete',
        [Posts::class, 'delete']
    )->name('postdelete');

    Route::get(
        '/posts/trashed',
        [Posts::class, 'trashed']
    )->name('trashedbox');

    Route::resource(
        '/posts',
        Posts::class
    );
    // ------------------- //


    // Category Routes
    // ------------------- //

    Route::resource(
        '/categories',
        Categories::class
    );
    // ------------------- //


    // Page Routes
    // ------------------- //
    Route::delete(
        '/pages/{id}/delete',
        [Pages::class, 'delete']
    )->name('pagedelete');

    Route::get(
        '/pages/trashed',
        [Pages::class, 'trashed']
    )->name('pagetrashedbox');

    Route::resource(
        '/pages',
        Pages::class
    );
    // ------------------- //

    // Gallery Routes
    // ------------------- //

    Route::resource(
        '/gallery',
        Gallery::class
    );

    // ------------------- //

    // Setting Routes
    // ------------------- //

    Route::resource(
        '/settings',
        Settings::class
    );

    // ------------------- //
});

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get(
    '/',
    [Homepage::class, 'index']
)->name('homepage');

Route::post(
    '/settings/mode',
    [Homepage::class, 'changeMode']
)->name('changeMode');

Route::get(
    '/{ctg}',
    [Homepage::class, 'categorypage']
)->name('categorypage');

Route::get(
    '/page/{slug}',
    [Homepage::class, 'pagepage']
)->name('pagepage');

Route::get(
    '/{ctg}/{slug}',
    [Homepage::class, 'singlepage']
)->name('singlepost');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'blg_categories';

    public function getPosts()
    {
        return $this->hasMany(Post::class, 'category', 'id')->orderBy('created_at', 'DESC');
    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('site_title', 'Blog')
@section('site_section', 'Categories')


@section('title', 'Categories')


@section('blog_name', 'AHC')
@section('site_address', 'http://127.0.0.1:8000')

@section('copyright', 'Copyright &copy; 2018 <div class="bullet"></div> All rights reserved.')

@section('dashboard')

<div class="section-body">
  <div class="row mt-4">
    <div class="col-12 col-md-12 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h4>New Categories</h4>
        </div>
        <div class="card-body">
          <form method="post" action="{{route('categories.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label>Name</label>
                <div class="">
                    <input type="text" class="form-control" name="categoryname" value="{{ old('categoryname') ?? '' }}" autocomplete="off">
                </div>
            </div>
            <div class="form-group">
                <label>Url</label>
                <div class="">
                    <input type="text" class="form-control" name="categoryslug" value="{{ old('categoryslug') ?? '' }}" autocomplete="off">
                </div>
            </div>
            <div class="form-group text-right">
                <button type="submit" class="btn btn-primary btn-lg btn-icon icon-right" name="submit">
                    Create
                </button>
            </div>
        </form>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-12 col-lg-8">
      @if ($messages ?? '')
        <div class="alert alert-{{$messages['type'] ?? ''}} alert-dismissible show fade">
          <div class="alert-body">
            <button class="close" data-dismiss="alert">
              <span>×</span>
            </button>
            {{$messages['text'] ?? ''}}
          </div>
        </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4>All Categories</h4>
        </div>
        <div class="card-body">
          <div class="float-left">
            <select class="form-control selectric">
              <option>Action For Selected</option>
              <option>Move to Draft</option>
              <option>Move to Pending</option>
              <option>Delete Permanently</option>
            </select>
          </div>
          <div class="float-right">
            <form>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-append">
                  <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                </div>
              </div>
            </form>
          </div>
          <div class="clearfix mb-3"></div>
          <div class="table-responsive">
            <table class="table table-striped">
              <tr>
                <th class="pt-2">
                  <div class="custom-checkbox custom-checkbox-table custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                      class="custom-control-input" id="checkbox-all">
                    <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                  </div>
                </th>
                <th>Title</th>
                <th>Created At</th>
                <th>Posts</th>
                <th>Action</th>
              </tr>
              @foreach ($categories as $item)
              <tr>
                <td>
                  <div class="custom-checkbox custom-control">
                    <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                      id="{{$item->id}}">
                    <label for="{{$item->id}}" class="custom-control-label">&nbsp;</label>
                  </div>
                </td>
                <td>
                  <a href="{{route('categorypage',[$item->slug])}}">{{$item->name}}</a>
                </td>
                <td>
                  {{$item->created_at}}
                </td>
                <td>
                  {{$item->total}}
                </td>
                <td>
                    <a href="{{ route('categories.destroy', ['category'=> $item->id]) }}"
                      class="btn btn-icon btn-danger" onclick="event.preventDefault();
                    document.getElementById('delete-form-{{ $item->id }}').submit();">
                      <i class="fas fa-times"></i>
                    </a>
                    <form id="delete-form-{{ $item->id }}" action="{{ route('categories.destroy', ['category'=> $item->id]) }}"
                      method="POST" style="display: none;">
                      @method('DELETE');
                      @csrf
                    </form>
                </td>
              </tr>
              @endforeach
            </table>
          </div>
          <div class="float-right">
            <nav>
                {{$categories->links("pagination::bootstrap-4")}}
            </nav>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

@endsection